openapi: 3.1.0
info:
  title: SKki shoe server API
  version: 0.0.2
paths:
  /midashis/{midashi}:
    parameters:
      - name: midashi
        in: path
        required: true
        schema:
          type: string
          minLength: 1
    get:
      summary: Returns candidates for specified midashi
      responses:
        default:
          description: failed to execute API call
        "200":
          description: List of corresponding candidates are returned.
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: "#/components/schemas/candidate"
                  
            text/plain:
              schema:
                description: |
                  SKK辞書のエントリーと似た書式をしています。
                  各エントリはスラッシュ区切りとなっており、最初と最後にはスラッシュが存在しません。
                  各エントリは「候補」部と「アノーテーション」部から成っており、セミコロンによって区切られます。
                  アノーテーションがない場合でもセミコロンは存在しています。

                examples:
                  - 変;(変化)色が変わる/代;(代理)代わりに出席する/交;挨拶を交わす/替;世代が替わる/買;/換;/飼;/變;「変」の旧字/支;ささえる
                  - 時計;/徒刑;/土圭;=時計 NB:「時計」は当て字/都計;[略語]都市計画
                type: string
components:
  schemas:
    candidate:
      type: object
      required:
        - candidate
      properties:
        candidate:
          type: string
        annotation:
          type: string
