openapi: 3.1.0
info:
  title: SKki shoe server API
  version: 0.0.1
paths:
  /candidates:
    parameters:
      - name: midashi
        in: query
        required: true
        schema:
          type: string
          minimum: 1
    get:
      summary: Returns candidates for specified midashi
      responses:
        "200":
          description: List of corresponding candidates are returned.
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: "#/components/schemas/candidate"
                  
#             text/*:
#               schema:
#                 type: string
components:
  schemas:
    candidate:
      type: object
      properties:
        candidate:
          type: string
        annotation:
          type: string
