// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"io"
)

// Ref: #/components/schemas/candidate
type Candidate struct {
	Candidate  string    `json:"candidate"`
	Annotation OptString `json:"annotation"`
}

// GetCandidate returns the value of Candidate.
func (s *Candidate) GetCandidate() string {
	return s.Candidate
}

// GetAnnotation returns the value of Annotation.
func (s *Candidate) GetAnnotation() OptString {
	return s.Annotation
}

// SetCandidate sets the value of Candidate.
func (s *Candidate) SetCandidate(val string) {
	s.Candidate = val
}

// SetAnnotation sets the value of Annotation.
func (s *Candidate) SetAnnotation(val OptString) {
	s.Annotation = val
}

// MidashisMidashiGetDef is default response for MidashisMidashiGet operation.
type MidashisMidashiGetDef struct {
	StatusCode int
}

// GetStatusCode returns the value of StatusCode.
func (s *MidashisMidashiGetDef) GetStatusCode() int {
	return s.StatusCode
}

// SetStatusCode sets the value of StatusCode.
func (s *MidashisMidashiGetDef) SetStatusCode(val int) {
	s.StatusCode = val
}

func (*MidashisMidashiGetDef) midashisMidashiGetRes() {}

type MidashisMidashiGetOKApplicationJSON []Candidate

func (*MidashisMidashiGetOKApplicationJSON) midashisMidashiGetRes() {}

// SKK辞書のエントリーと似た書式をしています。
// 各エントリはスラッシュ区切りとなっており、最初と最後にはスラッシュが存在しません。
// 各エントリは「候補」部と「アノーテーション」部から成っており、セミコロンによって区切られます。
// アノーテーションがない場合でもセミコロンは存在しています。.
type MidashisMidashiGetOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MidashisMidashiGetOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*MidashisMidashiGetOKTextPlain) midashisMidashiGetRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
