// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// MidashisMidashiGetParams is parameters of GET /midashis/{midashi} operation.
type MidashisMidashiGetParams struct {
	Midashi string
}

func unpackMidashisMidashiGetParams(packed middleware.Parameters) (params MidashisMidashiGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "midashi",
			In:   "path",
		}
		params.Midashi = packed[key].(string)
	}
	return params
}

func decodeMidashisMidashiGetParams(args [1]string, argsEscaped bool, r *http.Request) (params MidashisMidashiGetParams, _ error) {
	// Decode path: midashi.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "midashi",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Midashi = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.Midashi)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "midashi",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
