// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CandidatesGetParams is parameters of GET /candidates operation.
type CandidatesGetParams struct {
	Midashi string
}

func unpackCandidatesGetParams(packed middleware.Parameters) (params CandidatesGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "midashi",
			In:   "query",
		}
		params.Midashi = packed[key].(string)
	}
	return params
}

func decodeCandidatesGetParams(args [0]string, argsEscaped bool, r *http.Request) (params CandidatesGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: midashi.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "midashi",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Midashi = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:    1,
					MinLengthSet: true,
					MaxLength:    0,
					MaxLengthSet: false,
					Email:        false,
					Hostname:     false,
					Regex:        nil,
				}).Validate(string(params.Midashi)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "midashi",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
