// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CandidatesGet implements GET /candidates operation.
//
// Returns candidates for specified midashi.
//
// GET /candidates
func (UnimplementedHandler) CandidatesGet(ctx context.Context, params CandidatesGetParams) (r []Candidate, _ error) {
	return r, ht.ErrNotImplemented
}
